/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConvertToSVMGUI.java
 *
 * Created on Jan 13, 2011, 9:14:28 AM
 */

package thesis;

import feature.Dictionary;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import lib.ConvertText;
import lib.ReadWriteFile;
import lib.TextFilter;

/**
 *
 * @author archer
 */
public class ConvertToSVMGUI extends javax.swing.JFrame {

    /** Creates new form ConvertToSVMGUI */
    public ConvertToSVMGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputTextField = new javax.swing.JTextField();
        outputTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        convertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Input file:");
        jLabel1.setName("jLabel1"); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel2.setText("Output file:");
        jLabel2.setName("jLabel2"); // NOI18N
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        inputTextField.setName("inputTextField"); // NOI18N
        mainPanel.add(inputTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 370, -1));

        outputTextField.setName("outputTextField"); // NOI18N
        mainPanel.add(outputTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 370, -1));

        browseButton.setText("Browse");
        browseButton.setName("browseButton"); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });
        mainPanel.add(browseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        saveButton.setText("Save to");
        saveButton.setName("saveButton"); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        mainPanel.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, -1));

        convertButton.setText("Convert");
        convertButton.setName("convertButton"); // NOI18N
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });
        mainPanel.add(convertButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 209, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setFileFilter(new TextFilter());
        int val = fc.showOpenDialog(null);

        if (val == JFileChooser.APPROVE_OPTION) {
            inputFile = fc.getSelectedFile();
            inputTextField.setText(inputFile.getAbsolutePath());
        }
    }//GEN-LAST:event_browseButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setFileFilter(new TextFilter());
        int val = fc.showSaveDialog(null);

        if (val == JFileChooser.APPROVE_OPTION) {
            outputFile = fc.getSelectedFile();
            outputTextField.setText(outputFile.getAbsolutePath());
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        // TODO add your handling code here:

        Dictionary dic = new Dictionary();
        String charSet = "UTF-8";
        try {

            PrintWriter out = ReadWriteFile.writeFile(outputFile, charSet);
//            System.out.println(ConvertText.convertToSVMFormat(inputFile));
            BufferedReader in = ReadWriteFile.readFile(inputFile, charSet);
            String line = null;
            while ((line = in.readLine()) != null) {
                if (!line.equals("")) {
                    out.println(ConvertText.convertToSVMFormat(line, dic));
                }
            }
            in.close();
//            out.print(ConvertText.convertToSVMFormat(inputFile));
            out.close();
            JOptionPane.showMessageDialog(null, "Convert done");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_convertButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertToSVMGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JButton convertButton;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField outputTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    private static File inputFile;
    private static File outputFile;
}
